### ISSUE TITLE
Build instructions for Ubuntu 16.04

### ISSUE THREAD

**Issue by mcowart123** [mapd/mapd-core#10]
The included commands to install/build the dependencies do not install bison++, which causes make to fail. Manually running `apt-get install bison++` fixes the issue.

**Comment by andrewseidl** [comment]
The very last batch of commands in the dependency build section builds and installs `bison++`. We don't have it in the list of packages installed with `apt` because it interacts with some of the build deps required for Thrift.

It's fine to install from `apt` after Thrift is built, you just might be forced to uninstall that package if you ever have to rebuild Thrift (it's a bug in how the build-deps and package conflicts are set up in the repositories, not an actual issue with Thrift/flex/bison++).

**Comment by mcowart123** [comment]
I could not get make to run successfully (it failed looking for flex) until I manually did an apt install of bison++. This was after running all the dependency builds. I put all the dependency commands into a script I ran as root (altering it to remove any sudo). I'm not going to say it's impossible there were any errors, but I didn't notice any in the output.
