### ISSUE TITLE
Problems set null jdbc

### ISSUE THREAD

**Issue by andrelucasti** [mapd/mapd-core#179]
I have problem that when write my insert in the MapD through JDBC,  with some parameters NULL using 
`statement.setNull(parameterIndex, null)` it return exception 

Caused by: java.sql.SQLException: Query failed : Syntax error at: ,
	at com.mapd.jdbc.MapDStatement.executeQuery(MapDStatement.java:69) 

the problem is that the mapd not support blank paramters ... 

someone help me...

Thanks.

**Comment by RalphLoen** [comment]
Hello Andre,
Since MapD itself doesn't support dynamic parameters, JDBC simulates this by substituting literal values for the question marks in the query.  The current JDBC code mistakenly substitutes an empty string for the setNull method.  When I substituted the string NULL, setNull() succeeded.  I should have a fix available shortly at driver version 1.2.

**Comment by RalphLoen** [comment]
e49f213 on ralph/setNull fixes the problem.

**Comment by andrelucasti** [comment]
Thanks for attention @RalphLoen .
I did not find the commit "e49f213 on ralph/setNull fixes the problem."

Can you give me the commit link ? 

Or... If i download it  in the official site i will have the driver JDBC updated?

**Comment by RalphLoen** [comment]
Hello Andre,
The change has not yet been approved for inclusion in our internal master code repository.  After submission to the internal repository, pushes are periodically made to the public repository, at which point you can pull the fix into your code.

I'll ask Monday if we can get this moving.

**Comment by dwayneberry** [comment]
closed with a8ef9182deee5
