### ISSUE TITLE
Thrift version used in Java codebase needs updating

### ISSUE THREAD

**Issue by baank** [mapd/mapd-core#80]
There seems to be a compatibility issue.

If you use thrift to generate the Java files using mapd.thrift then you need version 0.10.0 otherwise it won't work (fails due to lack of recursion). However the entire Java codebase uses 0.9.3.

These need to be kept the same.

**Comment by andrewseidl** [comment]
It sounds like you're using `mvn` directly instead of calling it through CMake. When doing so you'll need to tell Maven which version of the Thrift compiler you used to generate the bindings so that it can grab the correct Thrift client libraries. This is exposed with the `thrift.version` property.

Something like:

    mvn install -Dthrift.version=$(thrift --version | grep -o "[0-9].*")

assuming that the `thrift` in your path is the same one used to generate the bindings.

**Comment by baank** [comment]
Then the issue should be changed to remove the thrift.verson property set in all of the pom.xml.

Also it's related to the other issues but we shouldn't need to run cmake in order to make changes to the JDBC driver.

**Comment by randyzwitch** [comment]
Closing this issue. In general, we have been updating Thrift as needed for continuing improvements to MapD. If this continues to be an issue with one of our current 4.0 releases, please feel free to open a new issue
